import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../worker/index.js';
const owner='owner@example.test', id='a1234567-1234-4123-8123-123456789abc';
function environment(){const sql=new DatabaseSync(':memory:'); for(const file of JSON.parse(readFileSync('drizzle/meta/_journal.json')).entries)sql.exec(readFileSync('drizzle/'+file.tag+'.sql','utf8')); sql.prepare('INSERT INTO interesses (id,sessao,criado_em,tipo,origem,pagina_entrada,pagina_atual,posicionamento,produto_id,produto_nome,marca,categoria,quiz,intencao) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,'session','2026-10-01T12:00:00Z','whatsapp_click','instagram','/','/','produto','PC-362','ASICS GEL-1130','ASICS','tenis','{"use":"casual"}','consulta'); return {sql,PORTELA_ADMIN_EMAIL:owner,DB:{prepare(query){let args=[];return {bind(...v){args=v;return this;},async first(){return sql.prepare(query).get(...args)||null;},async all(){return {results:sql.prepare(query).all(...args)};},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:r.changes}};}};}}};}
function req(path='/api/atendimento',email=owner,body,origin='https://portela.test'){return new Request('https://portela.test'+path,{method:body?'PATCH':'GET',headers:{...(email?{'oai-authenticated-user-email':email,'oai-authenticated-user-id':'signed-user'}:{}),origin,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});}
test('anonymous cannot read interests or bypass the protected page filename',async()=>{const e=environment();assert.equal((await worker.fetch(req('/api/atendimento',null),e)).status,401);const r=await worker.fetch(req('/atendimento.html',null),e);assert.equal(r.status,302);assert.match(r.headers.get('location'),/^\/signin-with-chatgpt\?/);});
test('another signed-in account cannot view or change attendance',async()=>{const e=environment();for(const path of ['/atendimento','/api/atendimento','/api/atendimento/base'])assert.equal((await worker.fetch(req(path,'other@example.test'),e)).status,403);assert.equal((await worker.fetch(req('/api/atendimento/'+id,'other@example.test',{status:'concluido',observacoes:'',revisao:0}),e)).status,403);});
test('missing owner configuration fails closed',async()=>{const e=environment();delete e.PORTELA_ADMIN_EMAIL;assert.equal((await worker.fetch(req(),e)).status,503);});
test('owner can filter real interests and receives no shared cache',async()=>{const e=environment();const r=await worker.fetch(req('/api/atendimento?marca=ASICS&status=novo'),e);assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/no-store/);const b=await r.json();assert.equal(b.items.length,1);assert.equal(b.items[0].produto_id,'PC-362');assert.equal(b.items[0].quiz.use,'casual');assert.equal((await (await worker.fetch(req('/api/atendimento?marca=Puma'),e)).json()).items.length,0);});
test('status and notes are saved with history; stale edits never overwrite them',async()=>{const e=environment();const body={status:'em_atendimento',observacoes:'Aguardar confirmação de tamanho.',revisao:0};const r=await worker.fetch(req('/api/atendimento/'+id,owner,body),e);assert.equal(r.status,200);const row=e.sql.prepare('SELECT * FROM interesses').get();assert.equal(row.status,body.status);assert.equal(row.observacoes,body.observacoes);const h=JSON.parse(row.historico);assert.equal(h.length,1);assert.equal(h[0].status_anterior,'novo');assert.equal(h[0].status,'em_atendimento');assert.equal((await worker.fetch(req('/api/atendimento/'+id,owner,{...body,status:'concluido'}),e)).status,409);assert.equal(e.sql.prepare('SELECT status FROM interesses').get().status,'em_atendimento');});
test('cross-origin updates, invalid status and excessive notes are rejected',async()=>{const e=environment();const b={status:'novo',observacoes:'',revisao:0};assert.equal((await worker.fetch(req('/api/atendimento/'+id,owner,b,'https://evil.test'),e)).status,403);assert.equal((await worker.fetch(req('/api/atendimento/'+id,owner,{...b,status:'vendido'}),e)).status,400);assert.equal((await worker.fetch(req('/api/atendimento/'+id,owner,{...b,observacoes:'x'.repeat(3001)}),e)).status,400);assert.equal((await worker.fetch(req('/api/atendimento/'+id,owner,{...b,revisao:-1}),e)).status,400);assert.equal((await worker.fetch(req('/api/atendimento?offset=-1'),e)).status,400);});
test('unknown record and database outage do not pretend success',async()=>{const e=environment();assert.equal((await worker.fetch(req('/api/atendimento/'+crypto.randomUUID(),owner,{status:'novo',observacoes:'',revisao:0}),e)).status,404);delete e.DB;assert.equal((await worker.fetch(req(),e)).status,503);});
test('knowledge includes the current catalog and unknown commercial conditions',async()=>{const r=await worker.fetch(req('/api/atendimento/base'),environment());assert.equal(r.status,200);const b=await r.json();assert.equal(b.produtos.length,390);assert.equal(b.ia_ativa,false);assert.equal(b.condicoes.preco,null);assert.equal(b.produtos.find(p=>p.id==='PC-362').marca,'ASICS');});
test('migration preserves previous interests and initializes notes without erasing records',()=>{const sql=new DatabaseSync(':memory:');const entries=JSON.parse(readFileSync('drizzle/meta/_journal.json')).entries;sql.exec(readFileSync('drizzle/'+entries[0].tag+'.sql','utf8'));sql.prepare('INSERT INTO interesses (id,sessao,criado_em,tipo,origem,pagina_entrada,pagina_atual,posicionamento,quiz,intencao) VALUES (?,?,?,?,?,?,?,?,?,?)').run(id,'existing','2026-09-30','quiz_complete','direto','/','/','quiz','{}','opcoes');for(const e of entries.slice(1))sql.exec(readFileSync('drizzle/'+e.tag+'.sql','utf8'));const r=sql.prepare('SELECT * FROM interesses').get();assert.equal(r.id,id);assert.equal(r.intencao,'opcoes');assert.equal(r.observacoes,'');assert.equal(r.historico,'[]');assert.equal(r.revisao,0);});
