import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {assistant} from '../worker/ia.js';
const catalog=JSON.parse(readFileSync('worker/catalog.json'));
function env(){const sql=new DatabaseSync(':memory:');for(const e of JSON.parse(readFileSync('drizzle/meta/_journal.json')).entries)sql.exec(readFileSync('drizzle/'+e.tag+'.sql','utf8'));return {sql,PORTELA_IA_ENABLED:'1',OPENAI_API_KEY:'test-secret',PORTELA_IA_MONTHLY_USD:'20',DB:{prepare(q){let args=[];return {bind(...a){args=a;return this;},async first(){return sql.prepare(q).get(...args)||null;},async run(){return sql.prepare(q).run(...args);}};}}};}
function req(body={messages:['Quero ASICS']},origin='https://portela.test'){return new Request('https://portela.test/api/ia',{method:'POST',headers:{origin,'content-type':'application/json','cf-connecting-ip':'192.0.2.1'},body:JSON.stringify(body)});}
const provider=async(url,opts)=>{const b=JSON.parse(opts.body);assert.equal(b.store,false);assert.equal(b.model,'gpt-4.1-mini-2025-04-14');assert.doesNotMatch(JSON.stringify(b),/SELECT|observacoes|historico/);return Response.json({output:[{content:[{type:'output_text',text:JSON.stringify({ids:['PC-362'],kind:'modelos'})}]}]});};
test('disabled deployment does not advertise AI or call the provider',async()=>{const e=env();e.PORTELA_IA_ENABLED='0';const r=await assistant(new Request('https://portela.test/api/ia'),e,catalog);assert.deepEqual(await r.json(),{enabled:false});assert.equal((await assistant(req(),e,catalog,()=>{throw Error('must not call');})).status,503);});
test('AI uses canonical references and never exposes secrets or private records',async()=>{const r=await assistant(req(),env(),catalog,provider);assert.equal(r.status,200);const b=await r.json();assert.equal(b.products[0].id,'PC-362');assert.equal(b.products[0].marca,'ASICS');assert.doesNotMatch(JSON.stringify(b),/test-secret/);});
test('foreign origins, oversized conversations and missing configuration do not call the provider',async()=>{const no=()=>{throw Error('provider must not run');};assert.equal((await assistant(req({},'https://other.test'),env(),catalog,no)).status,403);assert.equal((await assistant(req({messages:['x'.repeat(601)]}),env(),catalog,no)).status,400);const e=env();delete e.OPENAI_API_KEY;assert.equal((await assistant(req(),e,catalog,no)).status,503);});
test('monthly reservation blocks beyond authorized $20 even with simultaneous callers',async()=>{const e=env();await assistant(req(),e,catalog,provider);e.sql.prepare("UPDATE ia_uso SET quantidade=399 WHERE id LIKE 'mes:%'").run();const results=await Promise.all([assistant(req(),e,catalog,provider),assistant(req(),e,catalog,provider)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,429]);});
test('commercial questions get a human confirmation and unknown model ids fail closed',async()=>{const mock=kind=>async()=>Response.json({output:[{content:[{type:'output_text',text:JSON.stringify({ids:kind==='modelos'?['PC-999']:[],kind})}]}]});const b=await (await assistant(req(),env(),catalog,mock('condicoes'))).json();assert.match(b.message,/confirmad/);assert.equal(b.products.length,0);assert.equal((await assistant(req(),env(),catalog,mock('modelos'))).status,503);});
test('IP allowance and upstream failure retain the monthly reservation',async()=>{const e=env();for(let i=0;i<12;i++)assert.equal((await assistant(req(),e,catalog,provider)).status,200);assert.equal((await assistant(req(),e,catalog,provider)).status,429);const f=env();assert.equal((await assistant(req(),f,catalog,async()=>new Response('',{status:429}))).status,503);assert.equal(f.sql.prepare("SELECT quantidade FROM ia_uso WHERE id LIKE 'mes:%'").get().quantidade,1);});
