import test from 'node:test';
import assert from 'node:assert/strict';
import {catalogMedia} from '../worker/catalog-media.js';
const body=new Uint8Array([82,73,70,70,4,0,0,0,87,69,66,80]);
const sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',body)),n=>n.toString(16).padStart(2,'0')).join('');
const key='media/catalogo/adidas/123/001.webp',registry={[key]:{sha256:sha,bytes:body.length}};
function setup(){const objects=new Map();return {objects,env:{PORTELA_ASSET_IMPORT_ENABLED:'1',PORTELA_ASSET_IMPORT_TOKEN:'test-secret',BUCKET:{async get(k){return objects.get(k)||null},async head(k){return objects.get(k)||null},async put(k,b,opts){objects.set(k,{body:b,httpEtag:'etag',customMetadata:opts.customMetadata})}}}};}
function req(token='test-secret',data=body,part='adidas/123/001.webp'){return new Request('https://example.test/api/catalogo/imagens/'+part,{method:'PUT',headers:{authorization:'Bearer '+token,'content-type':'image/webp'},body:data});}
test('image uploads require the configured secret and an enabled import window',async()=>{const {env}=setup();assert.equal((await catalogMedia(req('wrong'),env,registry)).status,401);env.PORTELA_ASSET_IMPORT_ENABLED='0';assert.equal((await catalogMedia(req(),env,registry)).status,401);});
test('only registered immutable WebP bytes can be uploaded',async()=>{const {env,objects}=setup();assert.equal((await catalogMedia(req(),env,registry)).status,201);assert.equal(objects.size,1);assert.equal((await catalogMedia(req(),env,registry)).status,200);assert.equal((await catalogMedia(req('test-secret',body,'other/123/001.webp'),env,registry)).status,404);assert.equal((await catalogMedia(req('test-secret',new Uint8Array(12)),env,registry)).status,422);});
test('registered images are public but arbitrary bucket keys stay inaccessible',async()=>{const {env}=setup();await catalogMedia(req(),env,registry);const r=await catalogMedia(new Request('https://example.test/'+key),env,registry);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/webp');assert.match(r.headers.get('cache-control'),/public/);assert.equal((await catalogMedia(new Request('https://example.test/media/catalogo/private/secret'),env,registry)).status,404);});
test('missing image falls back to retained static asset and storage failure is recoverable',async()=>{const {env}=setup();env.ASSETS={fetch:async()=>new Response('legacy',{status:200})};assert.equal(await (await catalogMedia(new Request('https://example.test/'+key),env,registry)).text(),'legacy');env.BUCKET.get=async()=>{throw Error('storage outage')};assert.equal((await catalogMedia(new Request('https://example.test/'+key),env,registry)).status,503);});
test('an existing object with different bytes cannot be silently accepted or overwritten',async()=>{const {env,objects}=setup();objects.set(key,{customMetadata:{sha256:'different'}});assert.equal((await catalogMedia(req(),env,registry)).status,409);assert.equal(objects.get(key).customMetadata.sha256,'different');});
